import Head from "next/head";
import { Button } from "~/components/ui/button";
import { Input } from "~/components/ui/input";
import Link from "next/link";
import { Label } from "~/components/ui/label";
import { api } from "~/utils/api";

export default function Home() {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-full  items-center justify-center">
        <div className="w-72 space-y-4 rounded-xl text-stone-950">
          <h1 className="scroll-m-20 text-center text-4xl font-extrabold tracking-tight lg:text-5xl">
            Colibri
          </h1>
          <form method="post" className="flex flex-col gap-6">
            <div className="space-y-2">
              <Label htmlFor="username">username</Label>
              <Input type="text" name="username" placeholder="rickastley" />
            </div>
            <div className="space-y-2">
              <Label htmlFor="password" className="block">
                password
              </Label>
              <Input placeholder="••••••••" type="password" name="password" />
              <small className="text-sm text-muted-foreground">
                we recommend using a password manager
              </small>
            </div>
            <Button
              asChild
              className="rounded-lg bg-blue-600 py-2 font-bold text-blue-50 transition-all hover:bg-blue-700"
            >
              <Link href="/dashboard" replace>
                Dashboard
              </Link>
            </Button>
          </form>

          <a
            href="#"
            className="text-sm font-medium leading-none text-blue-600 underline"
          >
            Forgot your password?
          </a>
        </div>
      </main>
    </>
  );
}
